{% set name = "jupyterlab_vim" %}
{% set version = "0.14.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_vim-{{ version }}.tar.gz
  sha256: 74794f2f298d19c9c362301ef63333681204fc90a18bec0b220c29383749e282

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging >=0.10,<2.0
    - jupyterlab >=3.1,<4.0
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - jupyterlab_vim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-vim
  summary: Code cell vim bindings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - fcollonval
    - ianhi
