{% set name = "jupyterlab_vim" %}
{% set version = "0.15.1+leave_current_mode" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/asford/jupyterlab-vim
  git_rev: leave_current_mode_default

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - nodejs <15.0
  host:
    - jupyter-packaging >=0.10,<2.0
    - jupyterlab >=3.1,<4.0
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - jupyterlab_vim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-vim
  summary: Code cell vim bindings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - fcollonval
    - ianhi
